<?php
return [
    "AF" => ["full" => "Afghanistan", "eu" => false],
    "AX" => ["full" => "Aland Islands", "eu" => false],
    "AL" => ["full" => "Albania", "eu" => false],
    "DZ" => ["full" => "Algeria", "eu" => false],
    "AS" => ["full" => "American Samoa", "eu" => false],
    "AD" => ["full" => "Andorra", "eu" => false],
    "AO" => ["full" => "Angola", "eu" => false],
    "AI" => ["full" => "Anguilla", "eu" => false],
    "AQ" => ["full" => "Antarctica", "eu" => false],
    "AG" => ["full" => "Antigua and Barbuda", "eu" => false],
    "AR" => ["full" => "Argentina", "eu" => false],
    "AM" => ["full" => "Armenia", "eu" => false],
    "AW" => ["full" => "Aruba", "eu" => false],
    "AU" => ["full" => "Australia", "eu" => false],
    "AT" => ["full" => "Austria", "eu" => true],
    "AZ" => ["full" => "Azerbaijan", "eu" => false],
    "BS" => ["full" => "Bahamas", "eu" => false],
    "BH" => ["full" => "Bahrain", "eu" => false],
    "BD" => ["full" => "Bangladesh", "eu" => false],
    "BB" => ["full" => "Barbados", "eu" => false],
    "BY" => ["full" => "Belarus", "eu" => false],
    "BE" => ["full" => "Belgium", "eu" => true],
    "BZ" => ["full" => "Belize", "eu" => false],
    "BJ" => ["full" => "Benin", "eu" => false],
    "BM" => ["full" => "Bermuda", "eu" => false],
    "BT" => ["full" => "Bhutan", "eu" => false],
    "BO" => ["full" => "Bolivia", "eu" => false],
    "BQ" => ["full" => "Bonaire, Sint Eustatius and Saba", "eu" => false],
    "BA" => ["full" => "Bosnia and Herzegovina", "eu" => false],
    "BW" => ["full" => "Botswana", "eu" => false],
    "BV" => ["full" => "Bouvet Island", "eu" => false],
    "BR" => ["full" => "Brazil", "eu" => false],
    "IO" => ["full" => "British Indian Ocean Territory", "eu" => false],
    "BN" => ["full" => "Brunei Darussalam", "eu" => false],
    "BG" => ["full" => "Bulgaria", "eu" => true],
    "BF" => ["full" => "Burkina Faso", "eu" => false],
    "BI" => ["full" => "Burundi", "eu" => false],
    "KH" => ["full" => "Cambodia", "eu" => false],
    "CM" => ["full" => "Cameroon", "eu" => false],
    "CA" => ["full" => "Canada", "eu" => false],
    "CV" => ["full" => "Cape Verde", "eu" => false],
    "KY" => ["full" => "Cayman Islands", "eu" => false],
    "CF" => ["full" => "Central African Republic", "eu" => false],
    "TD" => ["full" => "Chad", "eu" => false],
    "CL" => ["full" => "Chile", "eu" => false],
    "CN" => ["full" => "China", "eu" => false],
    "CX" => ["full" => "Christmas Island", "eu" => false],
    "CC" => ["full" => "Cocos (Keeling) Islands", "eu" => false],
    "CO" => ["full" => "Colombia", "eu" => false],
    "KM" => ["full" => "Comoros", "eu" => false],
    "CG" => ["full" => "Congo", "eu" => false],
    "CD" => ["full" => "Congo, Democratic Republic of the Congo", "eu" => false],
    "CK" => ["full" => "Cook Islands", "eu" => false],
    "CR" => ["full" => "Costa Rica", "eu" => false],
    "CI" => ["full" => "Cote D'Ivoire", "eu" => false],
    "HR" => ["full" => "Croatia", "eu" => true],
    "CU" => ["full" => "Cuba", "eu" => false],
    "CW" => ["full" => "Curacao", "eu" => false],
    "CY" => ["full" => "Cyprus", "eu" => true],
    "CZ" => ["full" => "Czech Republic", "eu" => true],
    "DK" => ["full" => "Denmark", "eu" => true],
    "DJ" => ["full" => "Djibouti", "eu" => false],
    "DM" => ["full" => "Dominica", "eu" => false],
    "DO" => ["full" => "Dominican Republic", "eu" => false],
    "EC" => ["full" => "Ecuador", "eu" => false],
    "EG" => ["full" => "Egypt", "eu" => false],
    "SV" => ["full" => "El Salvador", "eu" => false],
    "GQ" => ["full" => "Equatorial Guinea", "eu" => false],
    "ER" => ["full" => "Eritrea", "eu" => false],
    "EE" => ["full" => "Estonia", "eu" => true],
    "ET" => ["full" => "Ethiopia", "eu" => false],
    "FK" => ["full" => "Falkland Islands (Malvinas)", "eu" => false],
    "FO" => ["full" => "Faroe Islands", "eu" => false],
    "FJ" => ["full" => "Fiji", "eu" => false],
    "FI" => ["full" => "Finland", "eu" => true],
    "FR" => ["full" => "France", "eu" => true],
    "GF" => ["full" => "French Guiana", "eu" => false],
    "PF" => ["full" => "French Polynesia", "eu" => false],
    "TF" => ["full" => "French Southern Territories", "eu" => false],
    "GA" => ["full" => "Gabon", "eu" => false],
    "GM" => ["full" => "Gambia", "eu" => false],
    "GE" => ["full" => "Georgia", "eu" => false],
    "DE" => ["full" => "Germany", "eu" => true],
    "GH" => ["full" => "Ghana", "eu" => false],
    "GI" => ["full" => "Gibraltar", "eu" => false],
    "GR" => ["full" => "Greece", "eu" => true],
    "GL" => ["full" => "Greenland", "eu" => false],
    "GD" => ["full" => "Grenada", "eu" => false],
    "GP" => ["full" => "Guadeloupe", "eu" => false],
    "GU" => ["full" => "Guam", "eu" => false],
    "GT" => ["full" => "Guatemala", "eu" => false],
    "GG" => ["full" => "Guernsey", "eu" => false],
    "GN" => ["full" => "Guinea", "eu" => false],
    "GW" => ["full" => "Guinea-Bissau", "eu" => false],
    "GY" => ["full" => "Guyana", "eu" => false],
    "HT" => ["full" => "Haiti", "eu" => false],
    "HM" => ["full" => "Heard Island and Mcdonald Islands", "eu" => false],
    "VA" => ["full" => "Holy See (Vatican City State)", "eu" => false],
    "HN" => ["full" => "Honduras", "eu" => false],
    "HK" => ["full" => "Hong Kong", "eu" => false],
    "HU" => ["full" => "Hungary", "eu" => true],
    "IS" => ["full" => "Iceland", "eu" => false],
    "IN" => ["full" => "India", "eu" => false],
    "ID" => ["full" => "Indonesia", "eu" => false],
    "IR" => ["full" => "Iran, Islamic Republic of", "eu" => false],
    "IQ" => ["full" => "Iraq", "eu" => false],
    "IE" => ["full" => "Ireland", "eu" => true],
    "IM" => ["full" => "Isle of Man", "eu" => false],
    "IL" => ["full" => "Israel", "eu" => false],
    "IT" => ["full" => "Italy", "eu" => true],
    "JM" => ["full" => "Jamaica", "eu" => false],
    "JP" => ["full" => "Japan", "eu" => false],
    "JE" => ["full" => "Jersey", "eu" => false],
    "JO" => ["full" => "Jordan", "eu" => false],
    "KZ" => ["full" => "Kazakhstan", "eu" => false],
    "KE" => ["full" => "Kenya", "eu" => false],
    "KI" => ["full" => "Kiribati", "eu" => false],
    "KP" => ["full" => "Korea, Democratic People's Republic of", "eu" => false],
    "KR" => ["full" => "Korea, Republic of", "eu" => false],
    "XK" => ["full" => "Kosovo", "eu" => false],
    "KW" => ["full" => "Kuwait", "eu" => false],
    "KG" => ["full" => "Kyrgyzstan", "eu" => false],
    "LA" => ["full" => "Lao People's Democratic Republic", "eu" => false],
    "LV" => ["full" => "Latvia", "eu" => true],
    "LB" => ["full" => "Lebanon", "eu" => false],
    "LS" => ["full" => "Lesotho", "eu" => false],
    "LR" => ["full" => "Liberia", "eu" => false],
    "LY" => ["full" => "Libyan Arab Jamahiriya", "eu" => false],
    "LI" => ["full" => "Liechtenstein", "eu" => false],
    "LT" => ["full" => "Lithuania", "eu" => true],
    "LU" => ["full" => "Luxembourg", "eu" => true],
    "MO" => ["full" => "Macao", "eu" => false],
    "MK" => ["full" => "Macedonia, the Former Yugoslav Republic of", "eu" => false],
    "MG" => ["full" => "Madagascar", "eu" => false],
    "MW" => ["full" => "Malawi", "eu" => false],
    "MY" => ["full" => "Malaysia", "eu" => false],
    "MV" => ["full" => "Maldives", "eu" => false],
    "ML" => ["full" => "Mali", "eu" => false],
    "MT" => ["full" => "Malta", "eu" => true],
    "MH" => ["full" => "Marshall Islands", "eu" => false],
    "MQ" => ["full" => "Martinique", "eu" => false],
    "MR" => ["full" => "Mauritania", "eu" => false],
    "MU" => ["full" => "Mauritius", "eu" => false],
    "YT" => ["full" => "Mayotte", "eu" => false],
    "MX" => ["full" => "Mexico", "eu" => false],
    "FM" => ["full" => "Micronesia, Federated States of", "eu" => false],
    "MD" => ["full" => "Moldova, Republic of", "eu" => false],
    "MC" => ["full" => "Monaco", "eu" => false],
    "MN" => ["full" => "Mongolia", "eu" => false],
    "ME" => ["full" => "Montenegro", "eu" => false],
    "MS" => ["full" => "Montserrat", "eu" => false],
    "MA" => ["full" => "Morocco", "eu" => false],
    "MZ" => ["full" => "Mozambique", "eu" => false],
    "MM" => ["full" => "Myanmar", "eu" => false],
    "NA" => ["full" => "Namibia", "eu" => false],
    "NR" => ["full" => "Nauru", "eu" => false],
    "NP" => ["full" => "Nepal", "eu" => false],
    "NL" => ["full" => "Netherlands", "eu" => true],
    "AN" => ["full" => "Netherlands Antilles", "eu" => false],
    "NC" => ["full" => "New Caledonia", "eu" => false],
    "NZ" => ["full" => "New Zealand", "eu" => false],
    "NI" => ["full" => "Nicaragua", "eu" => false],
    "NE" => ["full" => "Niger", "eu" => false],
    "NG" => ["full" => "Nigeria", "eu" => false],
    "NU" => ["full" => "Niue", "eu" => false],
    "NF" => ["full" => "Norfolk Island", "eu" => false],
    "MP" => ["full" => "Northern Mariana Islands", "eu" => false],
    "NO" => ["full" => "Norway", "eu" => false],
    "OM" => ["full" => "Oman", "eu" => false],
    "PK" => ["full" => "Pakistan", "eu" => false],
    "PW" => ["full" => "Palau", "eu" => false],
    "PS" => ["full" => "Palestinian Territory, Occupied", "eu" => false],
    "PA" => ["full" => "Panama", "eu" => false],
    "PG" => ["full" => "Papua New Guinea", "eu" => false],
    "PY" => ["full" => "Paraguay", "eu" => false],
    "PE" => ["full" => "Peru", "eu" => false],
    "PH" => ["full" => "Philippines", "eu" => false],
    "PN" => ["full" => "Pitcairn", "eu" => false],
    "PL" => ["full" => "Poland", "eu" => true],
    "PT" => ["full" => "Portugal", "eu" => true],
    "PR" => ["full" => "Puerto Rico", "eu" => false],
    "QA" => ["full" => "Qatar", "eu" => false],
    "RE" => ["full" => "Reunion", "eu" => false],
    "RO" => ["full" => "Romania", "eu" => true],
    "RU" => ["full" => "Russian Federation", "eu" => false],
    "RW" => ["full" => "Rwanda", "eu" => false],
    "BL" => ["full" => "Saint Barthelemy", "eu" => false],
    "SH" => ["full" => "Saint Helena", "eu" => false],
    "KN" => ["full" => "Saint Kitts and Nevis", "eu" => false],
    "LC" => ["full" => "Saint Lucia", "eu" => false],
    "MF" => ["full" => "Saint Martin", "eu" => false],
    "PM" => ["full" => "Saint Pierre and Miquelon", "eu" => false],
    "VC" => ["full" => "Saint Vincent and the Grenadines", "eu" => false],
    "WS" => ["full" => "Samoa", "eu" => false],
    "SM" => ["full" => "San Marino", "eu" => false],
    "ST" => ["full" => "Sao Tome and Principe", "eu" => false],
    "SA" => ["full" => "Saudi Arabia", "eu" => false],
    "SN" => ["full" => "Senegal", "eu" => false],
    "RS" => ["full" => "Serbia", "eu" => false],
    "CS" => ["full" => "Serbia and Montenegro", "eu" => false],
    "SC" => ["full" => "Seychelles", "eu" => false],
    "SL" => ["full" => "Sierra Leone", "eu" => false],
    "SG" => ["full" => "Singapore", "eu" => false],
    "SX" => ["full" => "Sint Maarten", "eu" => false],
    "SK" => ["full" => "Slovakia", "eu" => true],
    "SI" => ["full" => "Slovenia", "eu" => true],
    "SB" => ["full" => "Solomon Islands", "eu" => false],
    "SO" => ["full" => "Somalia", "eu" => false],
    "ZA" => ["full" => "South Africa", "eu" => false],
    "GS" => ["full" => "South Georgia and the South Sandwich Islands", "eu" => false],
    "SS" => ["full" => "South Sudan", "eu" => false],
    "ES" => ["full" => "Spain", "eu" => true],
    "LK" => ["full" => "Sri Lanka", "eu" => false],
    "SD" => ["full" => "Sudan", "eu" => false],
    "SR" => ["full" => "Suriname", "eu" => false],
    "SJ" => ["full" => "Svalbard and Jan Mayen", "eu" => false],
    "SZ" => ["full" => "Swaziland", "eu" => false],
    "SE" => ["full" => "Sweden", "eu" => true],
    "CH" => ["full" => "Switzerland", "eu" => false],
    "SY" => ["full" => "Syrian Arab Republic", "eu" => false],
    "TW" => ["full" => "Taiwan, Province of China", "eu" => false],
    "TJ" => ["full" => "Tajikistan", "eu" => false],
    "TZ" => ["full" => "Tanzania, United Republic of", "eu" => false],
    "TH" => ["full" => "Thailand", "eu" => false],
    "TL" => ["full" => "Timor-Leste", "eu" => false],
    "TG" => ["full" => "Togo", "eu" => false],
    "TK" => ["full" => "Tokelau", "eu" => false],
    "TO" => ["full" => "Tonga", "eu" => false],
    "TT" => ["full" => "Trinidad and Tobago", "eu" => false],
    "TN" => ["full" => "Tunisia", "eu" => false],
    "TR" => ["full" => "Turkey", "eu" => false],
    "TM" => ["full" => "Turkmenistan", "eu" => false],
    "TC" => ["full" => "Turks and Caicos Islands", "eu" => false],
    "TV" => ["full" => "Tuvalu", "eu" => false],
    "UG" => ["full" => "Uganda", "eu" => false],
    "UA" => ["full" => "Ukraine", "eu" => false],
    "AE" => ["full" => "United Arab Emirates", "eu" => false],
    "GB" => ["full" => "United Kingdom", "eu" => false],
    "US" => ["full" => "United States", "eu" => false],
    "UM" => ["full" => "United States Minor Outlying Islands", "eu" => false],
    "UY" => ["full" => "Uruguay", "eu" => false],
    "UZ" => ["full" => "Uzbekistan", "eu" => false],
    "VU" => ["full" => "Vanuatu", "eu" => false],
    "VE" => ["full" => "Venezuela", "eu" => false],
    "VN" => ["full" => "Viet Nam", "eu" => false],
    "VG" => ["full" => "Virgin Islands, British", "eu" => false],
    "VI" => ["full" => "Virgin Islands, U.s.", "eu" => false],
    "WF" => ["full" => "Wallis and Futuna", "eu" => false],
    "EH" => ["full" => "Western Sahara", "eu" => false],
    "YE" => ["full" => "Yemen", "eu" => false],
    "ZM" => ["full" => "Zambia", "eu" => false],
    "ZW" => ["full" => "Zimbabwe", "eu" => false]
];
