name: Deploy to staging
run-name: Deploy ${{ github.sha }} to forge by @${{ github.actor }}
on:
  push:
    branches:
      - 'staging'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://forge.laravel.com/servers/619584/sites/1835799/deploy/http?token=1Gp0IJVlNDIp7x0TTKdoMbTBC4pYVXDHAtOvJMr1
