name: Deploy to Digital ocean
run-name: Deploy ${{ github.sha }} to forge by @${{ github.actor }}
on:
  push:
    branches:
      - 'master-digital-ocean'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: https://forge.laravel.com/servers/854474/sites/2509650/deploy/http?token=qCVPpXDzqQTui1fCHU9BADRGKWq6yynHXvGsLqzi
